title: EEG解析入門
plugins:
  - jekyll-sitemap
permalink: pretty
theme: minima
defaults:
  - scope:
      path: ""
    values:
      layout: default


# これで GFM 記法維持しつつ kramdown で処理
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  auto_ids: true   # 見出しにidを自動付与（JS保険もあるが一応）