title: EEG解析入門
theme: minima   # とりあえず見た目はこれでOK
plugins:
  - jekyll-sitemap
permalink: pretty

# これで GFM 記法維持しつつ kramdown で処理
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span: true
    line_numbers: true   # 行番号ほしいなら true