title: EEG解析入門
theme: minima   # とりあえず見た目はこれでOK
plugins:
  - jekyll-sitemap

# これで GFM 記法維持しつつ kramdown で処理
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge